# Generated by Django 4.2.11 on 2026-03-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('mostrar_hora', models.BooleanField(default=False)),
                ('data_resultado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/images/membros/')),
                ('github', models.URLField(blank=True)),
                ('situacao', models.CharField(choices=[('BOLSISTA', 'Bolsista'), ('NAO_BOLSISTA', 'Não-Bolsista'), ('COLABORADOR', 'Colaborador'), ('EX_MEMBRO', 'Ex-membro')], default='COLABORADOR', max_length=12)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/images/technologies/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('publico', models.BooleanField(default=False)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado'), ('SUSPENSO', 'Suspenso'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('PLANEJAMENTO', 'Planejamento')], default='PLANEJAMENTO', max_length=15)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/images/projects/')),
                ('github', models.URLField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('membros', models.ManyToManyField(related_name='projetos', to='core.membro')),
                ('tecnologias', models.ManyToManyField(to='core.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('ativo', models.BooleanField(default=False)),
                ('semestre', models.IntegerField(choices=[(1, '1'), (2, '2')], default=2)),
                ('vagas_bolsista', models.IntegerField()),
                ('vagas_nao_bolsista', models.IntegerField()),
                ('vagas_colaborador', models.IntegerField()),
                ('inicio_inscricao', models.DateField()),
                ('fim_inscricao', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('edital', models.FileField(upload_to='static/edital/%Y/%m')),
                ('etapas', models.ManyToManyField(to='core.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('horas', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('membros', models.ManyToManyField(to='core.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projeto')),
            ],
        ),
    ]
