# Generated by Django 4.2.11 on 2026-03-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
