# Generated by Django 4.2.11 on 2026-03-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membro_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='sobrenome',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
