# Generated by Django 4.2.11 on 2026-03-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_membro_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='github',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
