# Generated by Django 4.2.11 on 2026-03-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_membro_github'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['nome', 'sobrenome']},
        ),
    ]
