# Generated by Django 4.2.11 on 2026-03-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_membro_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='github',
        ),
    ]
