# Generated by Django 4.2.11 on 2026-03-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_projeto_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
