# Generated by Django 4.2.11 on 2026-03-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projeto_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='publica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/tecnologias/'),
        ),
    ]
