# Generated by Django 4.2.11 on 2026-03-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoria_publica_alter_tecnologia_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='publica',
        ),
        migrations.AddField(
            model_name='categoria',
            name='interna',
            field=models.BooleanField(default=False),
        ),
    ]
