# Generated by Django 4.2.11 on 2026-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_categoria_publica_categoria_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='core.membro'),
        ),
    ]
