# Generated by Django 4.2.11 on 2026-04-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_projeto_membros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='fim',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='inicio',
            new_name='data_inicio',
        ),
    ]
