# Generated by Django 4.2.11 on 2026-04-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projeto_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/membros/capas/'),
        ),
    ]
