# Generated by Django 4.2.11 on 2026-04-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_membro_capa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processo',
            new_name='ProcessoSeletivo',
        ),
    ]
