# Generated by Django 4.2.11 on 2026-04-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_processo_processoseletivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoseletivo',
            name='email',
        ),
    ]
