# Generated by Django 4.2.11 on 2026-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_processoseletivo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='mostrar_hora',
        ),
        migrations.AddField(
            model_name='etapa',
            name='data_fim',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa',
            name='data_inicio',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='hora_resultado',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
