# Generated by Django 4.2.11 on 2026-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_etapa_fim_remove_etapa_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoseletivo',
            name='formulario',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
