# Generated by Django 4.2.11 on 2026-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_processoseletivo_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='data_resultado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
