# Generated by Django 4.2.11 on 2026-04-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_etapa_data_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
