# Generated by Django 4.2.11 on 2026-04-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_atividade_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, to='core.tecnologia'),
        ),
    ]
