# Generated by Django 4.2.11 on 2026-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_projeto_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
