# Generated by Django 4.2.11 on 2026-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_membro_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='fundos/')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='membro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='membros/capas/'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tecnologias/'),
        ),
    ]
