# Generated by Django 4.2.11 on 2026-05-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_configuracaosite_delete_usuario_alter_membro_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoseletivo',
            name='edital',
            field=models.FileField(upload_to='media/editais/<django.db.models.fields.IntegerField>/<django.db.models.fields.IntegerField>/'),
        ),
    ]
