# Generated by Django 4.2.11 on 2026-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_processoseletivo_edital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='fundos_site/'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='membros_capas/'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros_fotos/'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='edital',
            field=models.FileField(upload_to='editais/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos_fotos/'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tecnologias_logos/'),
        ),
    ]
