# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('ano', models.IntegerField(blank=True, choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], verbose_name='ano')),
                ('foto', models.ImageField(blank=True, upload_to='images/equipe/', verbose_name='foto')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub')),
            ],
            options={
                'verbose_name': 'membro de equipe',
                'verbose_name_plural': 'membros da equipe',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('membroequipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site2016.MembroEquipe')),
                ('situacao', models.CharField(choices=[('B', 'Bolsista'), ('N', 'Não-bolsista'), ('V', 'Voluntário'), ('E', 'Ex-membro')], max_length=1, verbose_name='situação no PET')),
            ],
            options={
                'verbose_name': 'bolsista',
                'verbose_name_plural': 'bolsistas',
            },
            bases=('site2016.membroequipe',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('membroequipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site2016.MembroEquipe')),
                ('descricao', models.CharField(max_length=250, verbose_name='descrição')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
            },
            bases=('site2016.membroequipe',),
        ),
    ]
