# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0002_auto_20170122_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], null=True, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/equipe/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub'),
        ),
    ]
