# Generated by Django 2.0.2 on 2018-02-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0003_auto_20170122_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data final')),
                ('mostrar_hora', models.BooleanField(default=False, verbose_name='mostrar hora')),
                ('resultado', models.TextField(verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'etapa',
                'verbose_name_plural': 'etapas',
            },
        ),
        migrations.CreateModel(
            name='ProcessoSeletivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='ano')),
                ('semestre', models.IntegerField(verbose_name='semestre')),
                ('vagas_bolsistas', models.IntegerField(default=12, verbose_name='vagas bolsistas')),
                ('vagas_nao_bolsistas', models.IntegerField(default=6, verbose_name='vagas não bolsistas')),
                ('data_inscricao_inicio', models.DateField(verbose_name='data inicial de inscrição')),
                ('data_inscricao_fim', models.DateField(verbose_name='data final de inscrição')),
                ('requisitos', models.TextField(default=' <li value="a)">Ser aluno regularmente matriculado no curso de Bacharelado em Ciência da Computação e estar cursando a partir do 2º (segundo) semestre de graduação; </li><li value="b)">Apresentar média ponderada semestral geral maior ou igual a 6.0 (seis);</li><li value="c)">Ter disponibilidade para se dedicar 20 (vinte) horas semanais nas atividadesdo programa;</li>', verbose_name='requisitos')),
                ('email_inscricao', models.EmailField(max_length=254, verbose_name='email para inscrição')),
                ('edital', models.FileField(upload_to='', verbose_name='edital')),
                ('etapas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site2016.EtapaPS')),
            ],
            options={
                'verbose_name': 'processo seletivo',
                'verbose_name_plural': 'processos seletivos',
            },
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], null=True, verbose_name='ano'),
        ),
    ]
