# Generated by Django 2.0.2 on 2018-02-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0004_auto_20180208_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoseletivo',
            name='etapas',
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='etapas',
            field=models.ManyToManyField(to='site2016.EtapaPS'),
        ),
    ]
