# Generated by Django 2.0.2 on 2018-02-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0005_auto_20180208_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaps',
            name='mostrar_resultado',
            field=models.BooleanField(default=False, verbose_name='mostrar resultado'),
        ),
        migrations.AlterField(
            model_name='etapaps',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data final'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='ano',
            field=models.IntegerField(default=2018, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='semestre',
            field=models.IntegerField(default=3, verbose_name='semestre'),
        ),
    ]
