# Generated by Django 2.0.2 on 2018-02-09 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0006_auto_20180208_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaps',
            name='ordem',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='etapaps',
            name='resultado',
            field=models.TextField(blank=True, null=True, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='ano',
            field=models.IntegerField(default=2018, validators=[django.core.validators.MinValueValidator(2010)], verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='semestre',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='semestre'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='vagas_bolsistas',
            field=models.PositiveIntegerField(default=12, verbose_name='vagas bolsistas'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='vagas_nao_bolsistas',
            field=models.PositiveIntegerField(default=6, verbose_name='vagas não bolsistas'),
        ),
    ]
