# Generated by Django 2.0.2 on 2018-02-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0009_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_de_projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='sigla')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'tecnologia',
                'verbose_name_plural': 'tecnologias',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('D', 'Em desenvolvimento'), ('A', 'Ativo'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='status do projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='categorias',
            field=models.ManyToManyField(to='site2016.Categoria_de_projeto', verbose_name='categorias do projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(to='site2016.Tecnologia', verbose_name='tecnologias utilizadas'),
        ),
    ]
