# Generated by Django 2.0.2 on 2018-02-13 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0011_auto_20180212_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, to='site2016.Tecnologia', verbose_name='tecnologias utilizadas'),
        ),
    ]
