# Generated by Django 2.0.2 on 2018-03-30 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0012_auto_20180212_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaps',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data inicial'),
            preserve_default=False,
        ),
    ]
