# Generated by Django 2.0.2 on 2018-03-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0013_auto_20180329_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processoseletivo',
            old_name='vagas_bolsistas',
            new_name='vagas_bolsista',
        ),
        migrations.RenameField(
            model_name='processoseletivo',
            old_name='vagas_nao_bolsistas',
            new_name='vagas_nao_bolsista',
        ),
    ]
