# Generated by Django 2.0.2 on 2018-03-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0014_auto_20180329_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaps',
            name='data_resultado',
            field=models.DateField(blank=True, null=True, verbose_name='data do resultado'),
        ),
    ]
