# Generated by Django 2.0.2 on 2018-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0015_auto_20180329_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='membroequipe',
            name='ano',
        ),
        migrations.AddField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='ano'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='situacao',
            field=models.CharField(choices=[('B', 'Bolsista'), ('N', 'Não-bolsista'), ('V', 'Voluntário'), ('E', 'Ex-membro')], default='Voluntário', max_length=1, verbose_name='situação no PET'),
            preserve_default=False,
        ),
    ]
