# Generated by Django 2.0.2 on 2018-04-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0016_auto_20180414_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='situacao',
        ),
    ]
