# Generated by Django 2.0.2 on 2018-04-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0017_remove_membroequipe_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='situacao',
            field=models.CharField(choices=[('B', 'Bolsista'), ('N', 'Não-bolsista'), ('V', 'Voluntário'), ('E', 'Ex-membro')], max_length=1, null=True, verbose_name='situação no PET'),
        ),
    ]
