# Generated by Django 2.0.2 on 2018-04-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0018_membroequipe_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], null=True, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='situacao',
            field=models.CharField(choices=[('B', 'Bolsista'), ('N', 'Não-bolsista'), ('V', 'Voluntário'), ('E', 'Ex-membro')], default='E', max_length=1, verbose_name='situação no PET'),
            preserve_default=False,
        ),
    ]
