# Generated by Django 2.0.2 on 2018-04-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0019_auto_20180414_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], null=True, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='imagem do projeto'),
        ),
    ]
