# Generated by Django 2.2.12 on 2020-06-05 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0020_auto_20180415_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], null=True, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='situacao',
            field=models.CharField(choices=[('B', 'Bolsista'), ('N', 'Não-bolsista'), ('C', 'Colaborador'), ('E', 'Ex-membro')], max_length=1, verbose_name='situação no PET'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='ano',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2010)], verbose_name='ano'),
        ),
    ]
