# Generated by Django 2.2.12 on 2020-07-04 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0021_auto_20200605_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(blank=True, choices=[('BCC', 'BCC'), ('EnC', 'EnC'), ('FIS', 'Física')], max_length=5, verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='site2016.Projeto', verbose_name='projetos'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='publico',
            field=models.BooleanField(default=True, verbose_name='público'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='semestre',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='semestre'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('D', 'Em desenvolvimento'), ('A', 'Ativo'), ('F', 'Finalizado'), ('S', 'Suspenso')], default='A', max_length=1, verbose_name='status do projeto'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('dia', models.DateField(verbose_name='dia')),
                ('horas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='horas')),
                ('minutos', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)], verbose_name='minutos')),
                ('membro', models.ManyToManyField(to='site2016.MembroEquipe', verbose_name='membros')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site2016.Projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
            },
        ),
    ]
