# Generated by Django 2.2.12 on 2020-07-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0022_auto_20200704_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='situacao',
            field=models.CharField(choices=[('B', 'Bolsista'), ('N', 'Não-bolsista'), ('V', 'Colaborador'), ('E', 'Ex-membro')], max_length=1, verbose_name='situação no PET'),
        ),
    ]
