# Generated by Django 2.2.12 on 2020-07-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0023_auto_20200704_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membroequipe',
            options={'ordering': ['nome'], 'verbose_name': 'membro de equipe', 'verbose_name_plural': 'membros da equipe'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['nome'], 'verbose_name': 'projeto', 'verbose_name_plural': 'projetos'},
        ),
    ]
