# Generated by Django 2.2.12 on 2020-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0024_auto_20200711_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('D', 'Em desenvolvimento'), ('P', 'Em planejamento'), ('A', 'Ativo'), ('F', 'Finalizado'), ('S', 'Suspenso')], default='A', max_length=1, verbose_name='status do projeto'),
        ),
    ]
