# Generated by Django 2.2.13 on 2021-03-03 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0025_auto_20200824_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoseletivo',
            name='vagas_colaborador',
            field=models.PositiveIntegerField(default=5, verbose_name='vagas colaboradores(as)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], null=True, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='ano',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2010)], verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='semestre',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='semestre'),
        ),
    ]
