# Generated by Django 2.2.24 on 2025-07-30 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2016', '0026_auto_20210303_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='membro',
            field=models.ManyToManyField(limit_choices_to=models.Q(_negated=True, situacao='E'), to='site2016.MembroEquipe', verbose_name='membros'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='ano',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2010)], verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='semestre',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='semestre'),
        ),
    ]
